/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
        "globalRow": any;
        "selectedRow": any;
        "tableData": any;
    }
    interface PieChart {
        /**
          * The data to feed into the d3 pie chart
         */
        "data": Array<any>;
        /**
          * The height of the chart
         */
        "height": number;
        /**
          * The width of the chart
         */
        "width": number;
    }
    interface TableChart {
        "columnHeaders": Array<string>;
        /**
          * The data to feed into the d3 table
         */
        "data": Array<object>;
        /**
          * The height of the chart
         */
        "height": number;
        "selectedRow": any;
        /**
          * The width of the chart
         */
        "width": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPieChartElement extends Components.PieChart, HTMLStencilElement {
    }
    var HTMLPieChartElement: {
        prototype: HTMLPieChartElement;
        new (): HTMLPieChartElement;
    };
    interface HTMLTableChartElement extends Components.TableChart, HTMLStencilElement {
    }
    var HTMLTableChartElement: {
        prototype: HTMLTableChartElement;
        new (): HTMLTableChartElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "pie-chart": HTMLPieChartElement;
        "table-chart": HTMLTableChartElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        "globalRow"?: any;
        "selectedRow"?: any;
        "tableData"?: any;
    }
    interface PieChart {
        /**
          * The data to feed into the d3 pie chart
         */
        "data"?: Array<any>;
        /**
          * The height of the chart
         */
        "height"?: number;
        /**
          * The width of the chart
         */
        "width"?: number;
    }
    interface TableChart {
        "columnHeaders"?: Array<string>;
        /**
          * The data to feed into the d3 table
         */
        "data"?: Array<object>;
        /**
          * The height of the chart
         */
        "height"?: number;
        "onRowClicked"?: (event: CustomEvent<any>) => void;
        "selectedRow"?: any;
        /**
          * The width of the chart
         */
        "width"?: number;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "pie-chart": PieChart;
        "table-chart": TableChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pie-chart": LocalJSX.PieChart & JSXBase.HTMLAttributes<HTMLPieChartElement>;
            "table-chart": LocalJSX.TableChart & JSXBase.HTMLAttributes<HTMLTableChartElement>;
        }
    }
}
